### PR TITLE
Update: Added resources for React JS

### PR DESCRIPTION
**Pull request by namangupta1399**
#ISSUE-NO

#### What does this PR do?
Added resources link for React JS

### CODE REVIEW

**Comment by namangupta1399** [comment]
@chryzcodez , I've added a resource for React JS. Please merge it so that other developers can benefit from it.
Thanks.

**Comment by amjadnoor** [comment]
@namangupta1399 Thanks for adding Reactjs resource. I am currently learning React it will help me a lot.

**Review by chryzcode — APPROVED** [review]

**Comment by chryzcode** [comment]
Thanks Naman

**Comment by namangupta1399** [comment]
That's great @AmjadNoor. Please do notify if you want to discuss anything related to React in discord. Will be happy to discuss. :)

**Pull request merged**
